image: node:10.13.0

stages:
  - deploy

deploy_prod:
  stage: deploy
  environment:
    name: production
    url: https://pcap-viz.netlify.app/
  only:
    - master
  script:
    - cd frontend
    - npm install netlify-cli
    - npm i
    - npm run build
    - npx netlify deploy --dir=build --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

deploy_dev:
  stage: deploy
  environment:
    name: dev
    url: https://pcap-viz-dev.netlify.app/
  only:
    - dev
  script:
    - cd frontend
    - npm install netlify-cli
    - npm i
    - npm run build
    - npx netlify deploy --dir=build --site $NETLIFY_DEV_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod